
# Site settings

# NB! Set your site's url, otherwise stuff will break :)

url: "https://oisinbates.github.io/"
#url: "https://oisinbates.com/"

# If you're hosting your site at a Project repository on GitHub pages
# (https://yourusername.github.io/repository-name)
# and NOT your user repository (https://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
#
# NB! Without this *nothing* will work, because it's used in every path :)

# baseurl: /personal-jekyll-theme
# baseurl: /oisinBates/oisinbates.github.io
#baseurl: /oisinbates.github.io
# Google tracking id

google-tracking-id: "UA-82049973-1"

# Forces https everywhere in your website, except when you serve it locally
# If you are not hosted on Github Pages, and your host doesn't support https
# then you should disable it

force-https: False

#############
# HTML Head #
#############

lang: "en"
author: "Oisín Bates"
title: "Oisín Bates"
description: "Blog and website of Oisín Bates."
keywords: "oisin, bates, personal, jekyll, theme"
favicon: "/img/ic_code_black.png"

################
# Header layout #
################

#black-favicon: "/img/black-lab-glass.ico"
#black-favicon: "/img/ic_code_white.png"

background-img: "../img/intro-bg.jpg"

##############################
# Dynamic Text on the Header #
##############################

dynamic-typing: True
shuffle: True # Shuffle the lines.
loop: True
loop-count: False # Set False for infinite loop, or set any number for finite loop.
type-speed: 10
start-delay: 200
delete-delay: 5000
lines: # You can add HTML Tags in the Text
  - text: "Irish Software Developer"
  - text: "Oisín Bates"

me-img: "/img/author.png"

##############################
# Color the browser elements #
##############################
color-browser: "#000000"
apple-status-bar-style: "black"

################
# Web app mode #
################

web-app-mode: False

# Icons for Web App mode

icon-36p: "/img/web-app/icon-36p.png"
icon-48p: "/img/web-app/icon-48p.png"
icon-72p: "/img/web-app/icon-72p.png"
icon-96p: "/img/web-app/icon-96p.png"
icon-144p: "/img/web-app/icon-144p.png"
icon-192p: "/img/web-app/icon-192p.png"

########
# Blog #
########

enable-gesture-navigation: True

post-preview-words: 56

paginate: 5

# email-share: True
# fb-share: True
# twitter-share: True
# linkedin-share: True
# reddit-share: True
# google-plus-share: True
# tumblr-share: True
# pinterest-share: True
# pocket-share: True
# vkontakte-share: True

disqus-shortname: ""

syntax-highlight: True

############
# Timeline #
############

events:
  #Logos used in low resolution, for informational purposes only, under a fair-use rationale.
  - image: "/img/timeline/waratek.jpg"
    date: "Nov. 2016 - May 2017"
    description: "*Pre-Sales Support Engineer*<br>Tested, demoed, administered, and supported Proof of Concept environments for a Java Runtime Application Security product."
  - image: "/img/timeline/elEx.jpg"
    date: "May 2016 - June 2016"
    description: "*Software Development Internship*<br> Worked on a serverless solution for contacting clients by phone and text."
  - image: "/img/timeline/UL.jpg"
    date: "Sep. 2015 - May 2016"
    description: "*Higher Diploma in Software Development*<br> Extra-curricular volunteering with local Coder Dojo project."
  - image: "/img/timeline/lbg.jpg"
    date: "Jan. 2015 - July 2015"
    description: "*PPI Review Assesor*<br>Worked on contract, reviewing missale complaints on Payment Protection Insurance(PPI) products."
  - image: "/img/timeline/UL.jpg"
    date: "2013 - 2014"
    description: "*M.A. History* <br> Dissertation on policing during the Anglo-Irish War. A chapter was chosen for publication in the academic journal *History Studies*."

# First image of the Timeline

timeline-img: "/img/timeline/default.png"

###########
# Contact #
###########

email: "bates.oisin@gmail.com"

################
# Author Blurb #
################

# The author blurb goes underneath blog posts.
# This works best when your author blurb image has a transparent background, or matches your site background color.

# # if the author_blurb is not set, then this feature is skipped
# author_blurb: "I am a Software Developer who studied at the University of Limerick. blurb yada yada yada"
# author_blurb_image: "/img/author.png"

##################
# Social Buttons #
##################

social:
  - title: "github"
    url: "https://github.com/oisinbates"
  - title: "linkedin"
    url: "https://ie.linkedin.com/in/oisinbates"
  # - title: "rss"
  #   url: "/feed.xml"

############
# 404 page #
############

err-404-img: "/img/labtocat.png"

##################
# GPG on Keybase #
##################

# keybase-username: johnsmith
# keybase-in-social: True
# keybase-in-footer: True

################################################################################

# NB! Tread carefully if you want to change the variables below this point!

# Sections shown in the index page

pages_list:
  About: 'about'
  Blog: 'latest-post'
  Timeline: 'timeline'
  Contact: 'contact'

# Exclusion list from the generated _site

exclude: ["LICENSE", "README.md", "CONTRIBUTING", "CONTRIBUTORS", "scripts"]

# Pagination path

paginate_path: "blog/page:num/"

# Enable minification SASS

sass:
  style: compressed

gems:
  - jekyll-paginate
  - jekyll-redirect-from
